---
title: "rgee - Landcover"
subtitle: "USGS National Land Cover Database"
output: 
  html_document:
    code_folding: "hide"
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 2
theme: united
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Requeriments

```{r message=FALSE}

library(tidyverse)
library(rgee)
library(sf)
library(cptcity)
source('utils.R')
ee_Initialize('antonybarja8@gmail.com',
              drive = TRUE,gcs = TRUE)

```

# Study area 

```{r  message=FALSE}
study_area <- read_sf('gpkg/study_area.shp') %>% st_simplify(preserveTopology = T,dTolerance = 0.001)

nc <- study_area %>% sf_as_ee()
box <- study_area %>% st_bbox() %>% st_as_sfc() %>% sf_as_ee()
Map$centerObject(nc , zoom = 9)
m0 <- Map$addLayer(
  nc,
  visParams = list(
    color = '#00000000',
    width = 8),
  name = 'study area' 
  )

m0
```

# Landcover

```{r message=FALSE}
years <- c(1992, 2001,2004,2006,2008,2011,2013,2016) %>% ee$List()
names_bands <- paste0('landcover',c(1992, 2001,2004,2006,2008,2011,2013,2016))

nldc <- years$
  map(ee_utils_pyfunc(function(x) {
    ee$ImageCollection("USGS/NLCD_RELEASES/2016_REL")$
      select(c('landcover'))$
      filter(ee$Filter$calendarRange(x, x, "year"))$
      sum()$
      clip(nc)
    })
    )

stack_nldc <- ee$ImageCollection(nldc)

viz <- list(
  min = 0, 
  max = 100,
  palette = c(
    "#466b9f","#d1def8","#dec5c5","#d99282","#eb0000",
    "#ab0000","#b3ac9f","#68ab5f","#1c5f2c","#b5c58f",
    "#af963c","#ccb879","#dfdfc2","#d1d182","#a3cc51",
    "#82ba9e","#dcd939","#ab6c28","#b8d9eb","#6c9fb8"
    )
  )

Map$centerObject(nc,zoom = 9)
m1 <- Map$addLayers(stack_nldc,viz,legend = TRUE) 
m1 + m0
```


# %Impervious

```{r message=FALSE}
years <- c(2001, 2006, 2011, 2016) %>% ee$List()
names_bands <- paste0('%impervious',c(2001,2006,2011,2016))
impervious <- years$
  map(ee_utils_pyfunc(function(x) {
    ee$ImageCollection("USGS/NLCD_RELEASES/2016_REL")$
      select('impervious')$
      filter(ee$Filter$calendarRange(x, x, "year"))$
      sum()$
      clip(nc)
    })
    )

nldc_impervious <- ee$ImageCollection(impervious)

viz <- list(
  min = 0,
  max = 100,
  palette = cpt(pal = 'mpl_viridis')
  )

Map$centerObject(nc,zoom = 9)
m2 <- Map$addLayers(nldc_impervious, visParams = viz, name = names_bands, legend = TRUE) 
m2 + m0 
```

# %Tree cover

```{r message=FALSE}
years <- c(2011, 2016) %>% ee$List()
names_bands <- paste0('%tree_cover',c(2011, 2016))
tree_cover <- years$
  map(ee_utils_pyfunc(function(x) {
    ee$ImageCollection("USGS/NLCD_RELEASES/2016_REL")$
      select('percent_tree_cover')$
      filter(ee$Filter$calendarRange(x, x, "year"))$
      sum()$
      clip(nc)
    })
    )

nldc_tree_cover <- ee$ImageCollection(tree_cover)

viz <- list(
  min = 0,
  max = 100,
  palette = cpt(pal = 'mpl_magma',rev = TRUE)
  )

Map$centerObject(nc,zoom = 9)
m3 <- Map$addLayers(nldc_tree_cover, visParams = viz, name = names_bands, legend = TRUE) 

m3 + m0
```


# NDVI  index 

```{r message=FALSE}
modis_years <- c(2010:2021) %>% ee$List()
names_bands <- sprintf('NDVI%s',2010:2021)
ndvi <- modis_years$
  map(ee_utils_pyfunc(function(x){
    ee$ImageCollection('MODIS/006/MOD13Q1')$
      select('NDVI')$
      filter(ee$Filter$calendarRange(x,x,"year"))$
      mean()$
      multiply(0.0001)$
      clip(nc)
    })
    )

stack_ndvi <- ee$ImageCollection(ndvi)
viz <- list(
  min = 0,
  max = 1,
  palette = cpt('grass_ndvi')
)

Map$centerObject(nc, zoom = 9)
m4 <- Map$addLayers(stack_ndvi,visParams = viz,name = names_bands)
m4 + m0 

```


# LTS - Tmax

```{r message=FALSE}

band_tmax <- sprintf('tmax%s%s',2010:2021,"[K°]")
tmax <- modis_years$
  map(ee_utils_pyfunc(function(x){
    ee$ImageCollection('MODIS/006/MOD11A1')$
      select('LST_Day_1km')$
      filter(ee$Filter$calendarRange(x,x,"year"))$
      max()$
      multiply(0.02)$
      clip(nc)
  })
  )

viz_tmax <- list(
  min =300,
  max =350,
  palette = cpt('grass_byr')
)

stack_tmax <- ee$ImageCollection(tmax)
Map$centerObject(nc, zoom = 9)
m5 <- Map$addLayers(stack_tmax, visParams = viz_tmax, name = band_tmax,legend = TRUE)
m5 + m0 

```

# LTS - Tmax

```{r message=FALSE}
band_tmin <- sprintf('tmin%s%s',2010:2021,"[K°]")
tmin <- modis_years$
  map(ee_utils_pyfunc(function(x){
    ee$ImageCollection('MODIS/006/MOD11A1')$
      select('LST_Day_1km')$
      filter(ee$Filter$calendarRange(x,x,"year"))$
      min()$
      multiply(0.02)$
      clip(nc)
  })
  )

viz_tmin <- list(
  min = 230,
  max = 280,
  palette = cpt('grass_byr')
)


stack_tmin <- ee$ImageCollection(tmin)
Map$centerObject(nc, zoom = 9)
m6 <- Map$addLayers(stack_tmin, visParams = viz_tmin, name = band_tmin,legend = TRUE)
m6 + m0 

```


# Creation of an environment dataset

```{r,  message=FALSE}
nldc <- stack_nldc$
  toBands()$
  select('7_landcover')$
  rename('nldc')

impervious <- nldc_impervious$
  toBands()$
  select('3_impervious')$
  rename('imp')

tree_cover <- nldc_tree_cover$
  toBands()$
  select('1_percent_tree_cover')$
  rename('tree')

ndvi <- stack_ndvi$
  toBands()$
  select('6_NDVI')$
  rename('ndvi') 
  
tmax <- stack_tmax$
  toBands()$
  select('6_LST_Day_1km')$
  rename('tmax')

tmin <- stack_tmin$
  toBands()$
  select('6_LST_Day_1km')$
  rename('tmin')

stack_evironment <- ee$Image(c(nldc,impervious,tree_cover,ndvi,tmax,tmin))
```


# Principal Component Analysis

```{r,  message=FALSE}
standar_environment <- img_to_stand(x = stack_evironment) 
environment_index <- pca_rgee(x = standar_environment) 
viz <- list(
  bands = c('pc3','pc2','pc1'),
  min = -2.5 ,
  max = 2.5
)

m7 <- Map$addLayer(environment_index,visParams = viz,name = 'pc3-pc2-pc1')
m7 + m0

```


# Table eingvector 

```{r echo=FALSE, message=FALSE}
library(kableExtra)
```

```{r, message=FALSE}

eingvector_rgee(x = standar_environment) %>% 
  kableExtra::kable(align = "lccrr") 
```


# Tabla eingvalues 

```{r, message=FALSE}
eingvalues_rgee(x = standar_environment) %>% 
  kableExtra::kable(align = "lccrr")
```




# Table of summarie 

```{r ,  message=FALSE}
table <- impor_pca(x = standar_environment) 

table %>% kableExtra::kable(align = "lccrr") 

```


# plot PCA

```{r , message=FALSE}

table %>% 
ggplot(aes(x = reorder(Component,variance),y = variance, fill = variance)) + 
  geom_bar(stat = 'identity') + 
  theme_bw() +
  coord_flip() + 
  labs(x = 'PCs', y = "%Total variance")

```



# Export an Image from GEE to local

```{r eval=FALSE, message=FALSE}
environment_index$bandNames()$getInfo()
download <- ee_as_raster(
  image = enviroment_index$select(c("pc1","pc2","pc3")),
  dsn = '/home/antonybarja/Descargas/img.tif', #ruta
  via = "drive",
  region = nc,
  scale = 1000 
  )

```
